### ISSUE TITLE
Request: Add place for initiative roll

### ISSUE THREAD

**Issue by piercemr** [ebeyer1/initiative-extension#4]
Need to know which each player rolled in order to know how to add future monster or players into the initiative order. Thinking a small UI visual, perhaps a superscript next to the name. 

Bonus: make characters sortable by the number.

**Comment by ebeyer1** [comment]
Added initiative input and display as its own table column for now: ca95e9aa3398ebc6050674c0925ce63701e222b3

May switch to a sub/super script at some point. But for now its there.

**Comment by ebeyer1** [comment]
Columns are sortable when you click them now: 3f0e568bdc67a55d60a60b5da32bc2d59bdf26a5
