### ISSUE TITLE
Request: Break New Entry field into multiple entrys

### ISSUE THREAD

**Issue by piercemr** [ebeyer1/initiative-extension#5]
Being able to add new monster or name is awesome. Would be great to also be able to add:

Name
Initiative Roll
HP
AC

While it can't be a single field, I would expect it to be easy to tab through to add these. I imagine something like this... 

![image](https://user-images.githubusercontent.com/691992/30769495-8f2bdacc-9fe7-11e7-8c56-bc3c29b032f5.png)

**Comment by ebeyer1** [comment]
Done with commit: 828a3bc24741c32fa557fca288e30f4d4822620d
